INSERT INTO TB_AUTHOR (NAME) VALUES ('Wesley Oliveira');
INSERT INTO TB_AUTHOR (NAME) VALUES ('João');

INSERT INTO TB_BOOK (NAME, AUTHOR_ID) VALUES ('Java v1', 1);
INSERT INTO TB_BOOK (NAME, AUTHOR_ID) VALUES ('Java v2', 2);